/// @description Reset edit mode
delete __EZRE_EDIT_INSTANCES_AVAILABLE;
__EZRE_EDIT_INSTANCES_AVAILABLE = {};
__EZRE_EDIT_ENABLED = false;
__EZRE_MODAL_STATE = __EZRE_MODAL_STATES.APPEAR;
__EZRE_MODAL_INST_TO_TRACK = noone;